name: Notify Discord on Push

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Get last commit message
    id: get_commit
    run: echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

  - name: Send message to Discord
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      COMMIT_MESSAGE: ${{ env.COMMIT_MSG }}
      COMMIT_AUTHOR: ${{ github.actor }}
    run: |
      curl -X POST -H "Content-Type: application/json" \
      -d "{\"content\": \"🚀 **${COMMIT_AUTHOR}** just pushed to **master**!\n📝 Commit: _${COMMIT_MESSAGE}_\"}" \
      $DISCORD_WEBHOOK_URL
