name: Notify Discord on Push

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.actor }}
        run: |
          if [ -z "$COMMIT_MESSAGE" ]; then
            COMMIT_MESSAGE="No commit message provided"
          fi
          curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"content\": \"🚀 **$COMMIT_AUTHOR** just pushed to **master**!\n💬 Commit Message: _${COMMIT_MESSAGE}_\"
          }" \
          $DISCORD_WEBHOOK_URL
