name: Notify Discord on Push

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message || github.event.commits[0].message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name || github.event.pusher.name }}
        run: |
          echo "Preparing message for Discord..."

          if [ -z "$COMMIT_MESSAGE" ]; then
            COMMIT_MESSAGE="No commit message provided 🚫"
          fi

          PAYLOAD=$(jq -n \
            --arg content "🚀 **$COMMIT_AUTHOR** just pushed to **master**! 📝 Commit: _$COMMIT_MESSAGE_" \
            '{content: $content}')

          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "$DISCORD_WEBHOOK_URL"
