name: Notify Discord on Push

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Get last commit message
      id: get_commit
      run: |
        echo "msg=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
        echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT

    - name: Notify Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        COMMIT_MESSAGE: ${{ steps.get_commit.outputs.msg }}
        COMMIT_AUTHOR: ${{ steps.get_commit.outputs.author }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"content\": \"🚀 **${COMMIT_AUTHOR}** just pushed to **master**!\n📝 Commit: _${COMMIT_MESSAGE}_\"}" \
        $DISCORD_WEBHOOK_URL
