name: Notify Discord on Push

on:
  push:
    branches:
      - main   # 如果你是push到master，就写master

jobs:
  send-discord-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send a simple notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.actor }}
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{
            \"content\": \"🚀 **$COMMIT_AUTHOR** just pushed to **personal-website**!\n💬 Commit Message: _${COMMIT_MESSAGE}_\"
          }" \
          $DISCORD_WEBHOOK_URL
